# Site settings
title: SDV
email: info@sdv.ml
url: https://sdvml.github.io/greyscale
description: "The Synthetic Data Vault"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: MIT Data To AI Lab

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sdv_ml
    # - title: facebook
    # - url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/sdv
    # - title: bitbucket
    # - url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/HDI-Project/SDV

# Build settings
markdown: kramdown
permalink: pretty
